### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by gusshawstewart** [githubschool/babyblue#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by gusshawstewart** [comment]
Hello!

**Comment by arunarackal83** [comment]
Hello Everyone

**Comment by ericalloyd** [comment]
Hola!

**Comment by Derek-Chang-BCBSA** [comment]
wasssup!!!

**Comment by RajaniNishanth** [comment]
Hello

**Comment by rajeshrajanala** [comment]
Hola

**Comment by Naseer2311** [comment]
Hi

**Comment by cs07886** [comment]
test

**Comment by Anudeepcse** [comment]
Hello

**Comment by srinivasgajarla** [comment]
Hello

**Comment by ramvee321** [comment]
Hello

**Comment by Saravana2020** [comment]
Managed to comment!

**Comment by saipbandi** [comment]
Hello

**Comment by mn06355** [comment]
Hello. Would like to be added invitation to be added as collaborator
